### ISSUE TITLE
New attack glitch

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#10]
Users of DefleMask tracker discovered a new discrepancy between the HW and how YMFM calculates the attack on some notes.

Here is an isolated .vgm: https://deflemask.com/attack_glitch_isolated.vgm

You'll hear that the last note in YMFM sounds slappy (with a much faster attack than the nuked one)
https://deflemask.com/attack_glitch_isolated_ymfm.wav
https://deflemask.com/attack_glitch_isolated_nuked.wav

Sidenote: This is not related to #7 , I have tested this fix candidate: https://github.com/aaronsgiles/ymfm/commit/d5914dafa747a9f2f1c448d4cb6e3198746acb22
but is not the case here.

**Comment by aaronsgiles** [comment]
Acknowledging this, just haven't had time to dig into it yet....
