### ISSUE TITLE
Wrong 12-bit PCM decoding

### ISSUE THREAD

**Issue by D15C0DE** [aaronsgiles/ymfm#13]
https://github.com/aaronsgiles/ymfm/blob/2a4e4493c7c91ac4fa590803d578f95523ff883c/src/ymfm_pcm.cpp#L563

The lower nibbles seem to be reversed. See https://github.com/ValleyBell/libvgm/commit/7a83aaebff6518ca13c243e413ea6847d732ddf1

**Comment by aaronsgiles** [comment]
Thanks for pointing this out! Fixed via a9c847b12f5ff8749e605bf3977dcf5fb61a4a38.
