### ISSUE TITLE
All chip support

### ISSUE THREAD

**Issue by 110-kenichi** [aaronsgiles/ymfm#19]
Do you have a plant to support all sound chips implemented by MAME?

I'm developing a DAW/MIDI synth with MAME engine.
( https://github.com/110-kenichi/mame )

However, it became very difficult to get the MAME engine source after big sound refactoring into the application.
( This is because the stream_sample_t class has been changed to read_stream_view/write_stream_view. )
So, I would like to change my MAME sound engine to the ymfm sound engine.

**Comment by aaronsgiles** [comment]
Sorry, not planning to support all chips. I may extend ymfm in the future for some other types of chips, but it's not a short-term effort so I wouldn't bank on it.

**Comment by 110-kenichi** [comment]
I see. Thank you!
