### ISSUE TITLE
Balance issue between YM2610 FM and SSG

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#23]
FM sine wave, silence, SSG square wave.
Up, YMFM
Down, previous MAME core.
![image](https://user-images.githubusercontent.com/14348106/145613069-a6292b83-7e03-4e1c-81cc-3d2dd195b682.png)

DefleMask tracker fixes this by dividing by 5 the SSG output.
https://deflemask.com/ym2610_balance_test.vgm

**Comment by aaronsgiles** [comment]
I don't really consider this an issue. It was a deliberate decision. 

The outputs for the SSG and FM are physically separate on the chip, and need to be volume controlled independently. I picked the current SSG output level as a reasonable default when playing some random VGM files. But each game has independent control over the volumes of the outputs, so there's really no one size fits all approach. The output level from MAME's old core is just as arbitrary. :)
