### ISSUE TITLE
YM2149F envelope mode emulation bug

### ISSUE THREAD

**Issue by tildearrow** [aaronsgiles/ymfm#25]
When turning on the hardware envelope on a channel, and setting that channel's tone and noise mode off, the channel stays silent and does not reflect the envelope value.

See issue https://github.com/tildearrow/furnace/issues/77 and [potential fix](https://github.com/tildearrow/furnace/commit/3b95baa60e2d59fdccb4d132597eff0ac0e2bdff).

**Comment by aaronsgiles** [comment]
Thanks for the report and pointer to a potential fix. I'll look into it.

**Comment by aaronsgiles** [comment]
This should be fixed with dc253c91dd600655bc6583ec16880ceee6901374
