### ISSUE TITLE
YM2151 Noise Freq is reversed

### ISSUE THREAD

**Issue by ZeroByteOrg** [aaronsgiles/ymfm#36]
For OPM, register 0x0F is noise frequency (bits 0-5) and noise_enable (bit 7)
In YMFM, the noise frequency output is highest when this value = 0 and lowest when this value = 1F.
The real hardware behaves in the reverse of this. (1F = highest freq, 00 = lowest freq)

We did a test using the same VGM data on two emulators and a real chip.
The emulator(s) using YMFM get the pitch backwards.
The real HW and emulators using either Nuked OPM or the previous MAME core produce
the expected results (1F = lowest, 00 = highest)

VGM attached
[Noise Sweep VGMs.zip](https://github.com/aaronsgiles/ymfm/files/8534465/Noise.Sweep.VGMs.zip)

**Comment by aaronsgiles** [comment]
Ooo, nice catch. I will look into it.

**Comment by ZeroByteOrg** [comment]
I had two different people with real YM2151 verify the behavior of real HW = pitch max = 1F, min = 00 - just to make sure I and the first person weren't crazy.

**Comment by aaronsgiles** [comment]
Thanks for the confirmation. I'm sure you're right, I am just distracted with another project ATM and will get back to this (and a couple of other pending issues) when I have some time.
