### ISSUE TITLE
ymf262 timer issue

### ISSUE THREAD

**Issue by elyosh** [aaronsgiles/ymfm#41]
According to the datasheet it seems that the timer period is not handled correctly on ymf262 : if the timer is set to 255 it should overflow immediately whereas currently it will overflow after 80us.

YMF262:
<img width="526" alt="ymf262_timer" src="https://user-images.githubusercontent.com/1732242/180960456-a2f14d63-8186-423b-8f8f-17570b2f229b.png">

YM3812:
<img width="472" alt="ym3812_timer" src="https://user-images.githubusercontent.com/1732242/180960869-c0915765-7412-4947-8972-e06dc8f30bc0.png">

**Comment by OBattler** [comment]
The YMF289B datasheet implies the same should be true for it as well.

**Comment by elyosh** [comment]
Closing since it was verified on real hardware that this is an error in the YMF262 datasheet, the timer actually behaves like with the YM3812.

> Detected a YMF262 OPL3 on port 0x388
Testing timer 1 with value 255
Timer overflow after 99 microseconds
Testing timer 1 with value 127
Timer overflow after 11374 microseconds
Testing timer 2 with value 255
Timer overflow after 187 microseconds
Testing timer 2 with value 127
Timer overflow after 45334 microseconds

**Comment by aaronsgiles** [comment]
Thanks for the reports and follow-ups. Glad this issue was resolved completely while I was on vacation. 😁
