### ISSUE TITLE
SSG-EG amplitude issue?

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#5]
We found a FM instrument that sounds really really different on the HW/Nuked vs the ymfm cores.
https://deflemask.com/bug_ssgeg_7_nuked.wav
https://deflemask.com/bug_ssgeg_7_ymfm.wav
https://deflemask.com/bug_ssgeg_7.vgm

It sounds different on amplitude but also on some of the inner works.

**Comment by LeonardoDemartino** [comment]
Here is a real hardware recording:
https://deflemask.com/bug_ssgeg_7_va6_real_hardware.wav

**Comment by aaronsgiles** [comment]
This most recent change gets closer, but not sure if it addresses the full issue. Let me know what you think.

**Comment by LeonardoDemartino** [comment]
A lot better indeed! We are investigating why even Nuked sounds different to HW. I'm closing this for now. Thanks a lot!
