### ISSUE TITLE
Alternative for missing set__volume() API?

### ISSUE THREAD

**Issue by stuerp** [aaronsgiles/ymfm#53]
I'm looking to upgrade an old version of ymfm in my foobar2000 plugin. The set__volume() API has been removed. The volume parameter has also disappeared from the calculations.

When I play a song with the latest version it frankly sounds wrong.

Can anybody point me to an alternate API, please?

**Comment by aaronsgiles** [comment]
Where did you see a set_volume() API? I don't remember one, but thought maybe my memory was faulty so I just checked out the initial version of the code and still don't see it.

Applying volume to the final output is trivial, so I can see why there's no API for it. Also, some chips have multiple outputs, and how they are mixed is dependent upon circuitry in the specific system you are emulating, so a general set_volume doesn't make sense in that context either.

Which emulators are you using that sound "wrong"?

**Comment by stuerp** [comment]
I started from a copy of [(PMDWin)](http://c60.la.coocan.jp) that uses 'a' copy of ymfm. I assumed the set___volume() calls were part of some older version of the ymfm code.

PMDWin uses the OPNA driver and tweaks the volume. I can leave those calls out and the songs play. However I'm not ready yet to adapt your lastest version to have the same behavior.

**Comment by aaronsgiles** [comment]
I took a look at PMDWin and it's a pretty hacked up version of my code. The files opna.* are not by me, so if you were using that as a basis, you might have trouble. You'd be better off taking the current ymfm version and using the ym2608 class directly (defined in ymfm_opn.h).
