### ISSUE TITLE
In CSM mode, only operator 1 is keyed on

### ISSUE THREAD

**Issue by TakayoshiKochi** [aaronsgiles/ymfm#57]
While I'm adopting ymfm to PC-8801 (YM2203 / YM2608B) emulator, I found that in CSM mode, only operator 1 is keyed on.
As in CSM mode, F-Numbers are set for all 4 operators independently, so keying on only operator 1 makes little sense.

Created a PR:
https://github.com/aaronsgiles/ymfm/pull/56

**Comment by aaronsgiles** [comment]
Thank you for this. I cannot remember why I changed it, but your fix does seem to be correct, so I have accepted the pull request.
