### ISSUE TITLE
OPL3 waveform 7 (derived square) doesn't seem right

### ISSUE THREAD

**Issue by devinacker** [aaronsgiles/ymfm#6]
I've been doing some experimentation with using ymfm for OPL3-based MIDI playback. So far almost everything sounds great, but I've noticed an issue where waveform 7 sounds noticeably different than it should, whether it's being used as a carrier or a modulator.

I recorded a simple "1-operator" test patch using Nuked-OPL3 (via Wohlstand's patch editor) and my own ymfm-based application for comparison:

![image](https://user-images.githubusercontent.com/4616298/119238745-731cba00-bb12-11eb-85b5-289b08a74226.png)
(Nuked on the left, ymfm on the right)

https://revenant1.net/opl3-dsq-nuked.ogg
https://revenant1.net/opl3-dsq-ymfm.ogg

It's especially apparent for patches that use it as a modulator, since the difference can have a pretty drastic effect on whatever other operators are involved.

**Comment by aaronsgiles** [comment]
Thanks for the report. Yes, my implementation of the derived square was on the list of things to revisit since I know it's probably pretty wrong. Since someone has now discovered my inadequacy 😉, I shall pop it to the top of the list of things to look at.

**Comment by aaronsgiles** [comment]
Quick check. Can you change line 99 of ymfm_opl.cpp to this:
```wf7[index] = (bitfield(index, 9) ? (index ^ 0x13ff) : index) << 3;```
and let me know if that works better?

**Comment by devinacker** [comment]
Yeah, that sounds much better. Thanks for the quick response!

**Comment by aaronsgiles** [comment]
Great, I'll commit it.
