### ISSUE TITLE
LFO speed appears to be a little bit slower than hardware or Nuked

### ISSUE THREAD

**Issue by LeonardoDemartino** [aaronsgiles/ymfm#8]
LFO is running considerably at a lower rate (confirmed on YM2612 and YM2610), it is really noticeable on high LFO speeds (like speed 7 MAX SPEED as shown in my example).
Image for comparison with NUKED/HW: https://deflemask.com/LFO_rate.png

https://deflemask.com/LFO_rate_test.vgm
https://deflemask.com/LFO_nuked.wav
https://deflemask.com/LFO_ymfm.wav

**Comment by aaronsgiles** [comment]
So this is interesting. At max speed, the LFO is documented to run at 72.2Hz given an 8MHz clock.

The YM2612 in your test runs at 7.67MHz, so the expected LFO frequency should be around 69.2Hz.

I had an off-by-one error which made my LFO one tick too slow. Fixing that and then frequency now lines up with the 69.2Hz value as expected.

However, nuked runs at around 83Hz. I tested my core by artificially creating an off-by-one error in the opposite direction and I perfectly matched nuked.

So two possibilities:
1. Nuked also has an off-by-one error (in the opposite direction) introduced during conversion from die shot to code.
2. The documentation is wrong about the LFO rates.

I'd say either possibility is likely. For now I'm correcting ymfm to match the documentation until we can get verification from hardware that nuked is correct here.

**Comment by LeonardoDemartino** [comment]
That's amazing!
I'll try to get a HW recording of https://deflemask.com/LFO_rate_test.vgm so we can be sure if the documentation is ok.

I'll let this open until we confirm this. Thanks a lot Aaron!

**Comment by LeonardoDemartino** [comment]
Ok, new info from the hardware:
https://deflemask.com/LFO_HW_Comparison.png

https://deflemask.com/LFO_hardware_genesismodel1.wav
https://deflemask.com/LFO_hardware_mdmodel1.wav
https://deflemask.com/LFO_hardware_VA6_TMSS.wav
https://deflemask.com/LFO_hardware_nomad.wav
https://deflemask.com/LFO_nuked.wav
https://deflemask.com/LFO_ymfm_new.wav

It seems that NUKED is synced (MDmodel1, VA6 TMSS, Nomad) but MODEL1 Genesis is a little bit slower? Maybe this is due to a particular problem with a particular motherboard revision but not as slower than YMFM.

**Comment by aaronsgiles** [comment]
Nice! Thanks for the quick confirmation. I just pushed the fix so ymfm will line up with the others.

I applied the fix generally, so please confirm that other LFO frequencies also line up, because they are now altered as well.

**Comment by LeonardoDemartino** [comment]
The other LFO frequencies seems to be lined up too. Thanks!

**Comment by aaronsgiles** [comment]
Awesome, thank you for confirming.
